namespace BitMapConverter
{
    public static class ISO8583DataElements
    {
        public static readonly Dictionary<int, string> DataElements = new Dictionary<int, string>
    {
        { 1, "Bitmap" },
        { 2, "Primary Account Number (PAN)" },
        { 3, "Processing Code" },
        { 4, "Amount, Transaction" },
        { 5, "Amount, Settlement" },
        { 6, "Amount, Cardholder Billing" },
        { 7, "Transmission Date and Time" },
        { 8, "Amount, Cardholder Billing Fee" },
        { 9, "Conversion Rate, Settlement" },
        { 10, "Conversion Rate, Cardholder Billing" },
        { 11, "Systems Trace Audit Number" },
        { 12, "Local Transaction Time" },
        { 13, "Local Transaction Date" },
        { 14, "Expiration Date" },
        { 15, "Settlement Date" },
        { 16, "Conversion Date" },
        { 17, "Capture Date" },
        { 18, "Merchant Type" },
        { 19, "Acquiring Institution Country Code" },
        { 20, "PAN Extended, Country Code" },
        { 21, "Forwarding Institution Country Code" },
        { 22, "Point of Service Entry Mode" },
        { 23, "Card Sequence Number" },
        { 24, "Function Code" },
        { 25, "Point of Service Condition Code" },
        { 26, "Point of Service Capture Code" },
        { 27, "Authorization Identification Response Length" },
        { 28, "Amount, Transaction Fee" },
        { 29, "Amount, Settlement Fee" },
        { 30, "Amount, Transaction Processing Fee" },
        { 31, "Amount, Settlement Processing Fee" },
        { 32, "Acquiring Institution Identification Code" },
        { 33, "Forwarding Institution Identification Code" },
        { 34, "Primary Account Number, Extended" },
        { 35, "Track 2 Data" },
        { 36, "Track 3 Data" },
        { 37, "Retrieval Reference Number" },
        { 38, "Authorization Identification Response" },
        { 39, "Response Code" },
        { 40, "Service Restriction Code" },
        { 41, "Card Acceptor Terminal Identification" },
        { 42, "Card Acceptor Identification Code" },
        { 43, "Card Acceptor Name/Location" },
        { 44, "Additional Response Data" },
        { 45, "Track 1 Data" },
        { 46, "Additional Data (ISO)" },
        { 47, "Additional Data (National)" },
        { 48, "Additional Data (Private)" },
        { 49, "Currency Code, Transaction" },
        { 50, "Currency Code, Settlement" },
        { 51, "Currency Code, Cardholder Billing" },
        { 52, "Personal Identification Number (PIN) Data" },
        { 53, "Security Related Control Information" },
        { 54, "Additional Amounts" },
        { 55, "Integrated Circuit Card (ICC) System Related Data" },
        { 56, "Reserved (ISO)" },
        { 57, "Reserved (National)" },
        { 58, "Reserved (National)" },
        { 59, "Reserved (Private)" },
        { 60, "Reserved (Private)" },
        { 61, "Reserved (Private)" },
        { 62, "Reserved (Private)" },
        { 63, "Reserved (Private)" },
        { 64, "Message Authentication Code (MAC)" },
        { 65, "Reserved for ISO Use" },
        { 66, "Amounts, Original Fees" },
        { 67, "Extended Payment Data" },
        { 68, "Country Code, Receiving Institution" },
        { 69, "Country Code, Settlement Institution" },
        { 70, "Network Management Information Code" },
        { 71, "Message Number" },
        { 72, "Data Record" },
        { 73, "Date, Action" },
        { 74, "Credits, Number" },
        { 75, "Credits, Reversal Number" },
        { 76, "Debits, Number" },
        { 77, "Debits, Reversal Number" },
        { 78, "Transfer Number" },
        { 79, "Transfer, Reversal Number" },
        { 80, "Inquiries, Number" },
        { 81, "Authorizations, Number" },
        { 82, "Credits, Processing Fee Amount" },
        { 83, "Credits, Transaction Fee Amount" },
        { 84, "Debits, Processing Fee Amount" },
        { 85, "Debits, Transaction Fee Amount" },
        { 86, "Credits, Amount" },
        { 87, "Credits, Reversal Amount" },
        { 88, "Debits, Amount" },
        { 89, "Debits, Reversal Amount" },
        { 90, "Original Data Elements" },
        { 91, "File Update Code" },
        { 92, "File Security Code" },
        { 93, "Response Indicator" },
        { 94, "Service Indicator" },
        { 95, "Replacement Amounts" },
        { 96, "Message Security Code" },
        { 97, "Amount, Net Settlement" },
        { 98, "Payee" },
        { 99, "Settlement Institution Identification Code" },
        { 100, "Receiving Institution Identification Code" },
        { 101, "File Name" },
        { 102, "Account Identification 1" },
        { 103, "Account Identification 2" },
        { 104, "Transaction Description" },
        { 105, "Reserved for ISO Use" },
        { 106, "Reserved for ISO Use" },
        { 107, "Reserved for ISO Use" },
        { 108, "Reserved for ISO Use" },
        { 109, "Reserved for ISO Use" },
        { 110, "Reserved for ISO Use" },
        { 111, "Reserved for ISO Use" },
        { 112, "Reserved for National Use" },
        { 113, "Reserved for National Use" },
        { 114, "Reserved for National Use" },
        { 115, "Reserved for National Use" },
        { 116, "Reserved for National Use" },
        { 117, "Reserved for National Use" },
        { 118, "Reserved for National Use" },
        { 119, "Reserved for National Use" },
        { 120, "Reserved for Private Use" },
        { 121, "Reserved for Private Use" },
        { 122, "Reserved for Private Use" },
        { 123, "Reserved for Private Use" },
        { 124, "Reserved for Private Use" },
        { 125, "Reserved for Private Use" },
        { 126, "Reserved for Private Use" },
        { 127, "Reserved for Private Use" },
        { 128, "Message Authentication Code (MAC) 2" },
        { 129, "Reserved for ISO Use" },
        { 130, "Reserved for ISO Use" },
        { 131, "Reserved for ISO Use" },
        { 132, "Reserved for ISO Use" },
        { 133, "Reserved for ISO Use" },
        { 134, "Reserved for ISO Use" },
        { 135, "Reserved for ISO Use" },
        { 136, "Reserved for ISO Use" },
        { 137, "Reserved for ISO Use" },
        { 138, "Reserved for ISO Use" },
        { 139, "Reserved for ISO Use" },
        { 140, "Reserved for ISO Use" },
        { 141, "Reserved for ISO Use" },
        { 142, "Reserved for ISO Use" },
        { 143, "Reserved for ISO Use" },
        { 144, "Reserved for ISO Use" },
        { 145, "Reserved for ISO Use" },
        { 146, "Reserved for ISO Use" },
        { 147, "Reserved for ISO Use" },
        { 148, "Reserved for ISO Use" },
        { 149, "Reserved for ISO Use" },
        { 150, "Reserved for ISO Use" },
        { 151, "Reserved for ISO Use" },
        { 152, "Reserved for ISO Use" },
        { 153, "Reserved for ISO Use" },
        { 154, "Reserved for ISO Use" },
        { 155, "Reserved for ISO Use" },
        { 156, "Reserved for ISO Use" },
        { 157, "Reserved for ISO Use" },
        { 158, "Reserved for ISO Use" },
        { 159, "Reserved for ISO Use" },
        { 160, "Reserved for National Use" },
        { 161, "Reserved for National Use" },
        { 162, "Reserved for National Use" },
        { 163, "Reserved for National Use" },
        { 164, "Reserved for National Use" },
        { 165, "Reserved for National Use" },
        { 166, "Reserved for National Use" },
        { 167, "Reserved for National Use" },
        { 168, "Reserved for National Use" },
        { 169, "Reserved for National Use" },
        { 170, "Reserved for National Use" },
        { 171, "Reserved for National Use" },
        { 172, "Reserved for National Use" },
        { 173, "Reserved for National Use" },
        { 174, "Reserved for National Use" },
        { 175, "Reserved for National Use" },
        { 176, "Reserved for National Use" },
        { 177, "Reserved for National Use" },
        { 178, "Reserved for National Use" },
        { 179, "Reserved for National Use" },
        { 180, "Reserved for National Use" },
        { 181, "Reserved for National Use" },
        { 182, "Reserved for National Use" },
        { 183, "Reserved for National Use" },
        { 184, "Reserved for National Use" },
        { 185, "Reserved for National Use" },
        { 186, "Reserved for National Use" },
        { 187, "Reserved for National Use" },
        { 188, "Reserved for National Use" },
        { 189, "Reserved for National Use" },
        { 190, "Reserved for National Use" },
        { 191, "Reserved for National Use" },
        { 192, "Reserved for National Use" }
    };
    }
}
